#!/bin/sh

## autoload vcs and colors
autoload -U colors && colors
parse_git_branch() {
        git symbolic-ref --short HEAD 2> /dev/null
}
setopt prompt_subst

# format our main prompt for hostname and current folder
PROMPT="%B%n %{$fg[blue]%}%~"
PROMPT+=" %{$fg[yellow]%}git:[$(parse_git_branch)]%{$reset_color%} $ "
