#!/bin/sh
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='nvim ~/.config/nvim/'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

case "$(uname -s)" in
Darwin)
    colorflag="--color=auto"
	;;
Linux)
	colorflag="-G"
    ;;
esac

# Colorize grep output (good for log files)
alias grep='grep ${colorflag}'
alias egrep='egrep ${colorflag}'
alias fgrep='fgrep ${colorflag}'

# Colorize ls
alias ls="ls ${colorflag}"
